# Generated by wwwyo/skillctrl tools/release; edit the generator, not this file.
class Skillctrl < Formula
  desc "Manage agent skills while preserving locally recorded intent"
  homepage "https://github.com/wwwyo/skillctrl"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/wwwyo/skillctrl/releases/download/v0.1.0/skillctrl_0.1.0_darwin_arm64.tar.gz"
      sha256 "4f170b91d5d95304ae15fafef8acf40b8ad4a6e5940294b0f12691f97c48597f"
    end
    on_intel do
      url "https://github.com/wwwyo/skillctrl/releases/download/v0.1.0/skillctrl_0.1.0_darwin_amd64.tar.gz"
      sha256 "73739f1f55bf877a42b0efdb84965ef80702db652adca8e80fb23cc4ce08d17f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wwwyo/skillctrl/releases/download/v0.1.0/skillctrl_0.1.0_linux_arm64.tar.gz"
      sha256 "e93044344740f867bd68722b5cbafe2414fe61f82dd676e2a96403275e3366fb"
    end
    on_intel do
      url "https://github.com/wwwyo/skillctrl/releases/download/v0.1.0/skillctrl_0.1.0_linux_amd64.tar.gz"
      sha256 "7782990b8b9faa431b559753c73b016c7a8cc14e3503cc4be7b86db16955c952"
    end
  end

  def install
    bin.install "skillctrl"
  end

  test do
    assert_match "skillctrl version v#{version}", shell_output("#{bin}/skillctrl --version")
    assert_match '"commands"', shell_output("#{bin}/skillctrl schema")
  end
end
