# Generated by wwwyo/skillctrl tools/release; edit the generator, not this file.
class Skillctrl < Formula
  desc "Manage agent skills while preserving locally recorded intent"
  homepage "https://github.com/wwwyo/skillctrl"
  version "0.3.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/wwwyo/skillctrl/releases/download/v0.3.1/skillctrl_0.3.1_darwin_arm64.tar.gz"
      sha256 "88bd311b547807462d2eb1a8c5fbd1fb0943e7923d74ea1af910a9df192d080e"
    end
    on_intel do
      url "https://github.com/wwwyo/skillctrl/releases/download/v0.3.1/skillctrl_0.3.1_darwin_amd64.tar.gz"
      sha256 "a3b93be3d85e8ad7584f2c73679cec0447e0107436dcc90094ba276754388ac5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wwwyo/skillctrl/releases/download/v0.3.1/skillctrl_0.3.1_linux_arm64.tar.gz"
      sha256 "691e8538de538e9e3f35a488fa77a7fa7956d68bce443da6075315fa6a967da9"
    end
    on_intel do
      url "https://github.com/wwwyo/skillctrl/releases/download/v0.3.1/skillctrl_0.3.1_linux_amd64.tar.gz"
      sha256 "a27a2a67db4e3a1f2e3ff8c2b2674d3ce674dba84cf2f73c409ae2d4ac9165c5"
    end
  end

  def install
    bin.install "skillctrl"
  end

  test do
    assert_match "skillctrl version v#{version}", shell_output("#{bin}/skillctrl --version")
    assert_match "hash", shell_output("#{bin}/skillctrl record --help")
  end
end
