# Generated by apps/syokan/scripts/generate-formula.ts in wwwyo/syokan (release 0.4.1).
# Do not edit by hand — the next release overwrites this file.
class Syokan < Formula
  desc "LLMs summon rich UI: post a JSON tree, an ephemeral view appears"
  homepage "https://github.com/wwwyo/syokan"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/wwwyo/syokan/releases/download/v0.4.1/syokan-darwin-arm64"
      sha256 "2a1813b2764e83a7b1fc1f6ef340057674675ddd063888d590df01d20e0e7e3d"
    end
    on_intel do
      url "https://github.com/wwwyo/syokan/releases/download/v0.4.1/syokan-darwin-x64"
      sha256 "70038df9ee3530c20e4b3f6b833bc570d1dcc7582829a9ff3e5dcc67daaf2292"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wwwyo/syokan/releases/download/v0.4.1/syokan-linux-arm64"
      sha256 "535588c3e818a61252d0285fd529b8a611fd055fb4589e65c119da76c61d6014"
    end
    on_intel do
      url "https://github.com/wwwyo/syokan/releases/download/v0.4.1/syokan-linux-x64"
      sha256 "db33f4fed4a6261b199fa294faf73d20b60b6bf8616e4f2f96aef92d4a824bb9"
    end
  end

  def install
    bin.install Dir["syokan-*"].first => "syokan"
  end

  test do
    assert_match "0.4.1", shell_output("#{bin}/syokan --version")
  end
end
