# Generated by apps/syokan/scripts/generate-formula.ts in wwwyo/syokan (release 0.3.1).
# Do not edit by hand — the next release overwrites this file.
class Syokan < Formula
  desc "LLMs summon rich UI: post a JSON tree, an ephemeral view appears"
  homepage "https://github.com/wwwyo/syokan"
  version "0.3.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/wwwyo/syokan/releases/download/v0.3.1/syokan-darwin-arm64"
      sha256 "581c33a53df4281625afc78d99430214e01c89f961cc7629e7a1d2e277bf37d0"
    end
    on_intel do
      url "https://github.com/wwwyo/syokan/releases/download/v0.3.1/syokan-darwin-x64"
      sha256 "50c0655ff75b030d3b1f68a61d723c98bd528b3c7530bfd2de33b211490d80c9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wwwyo/syokan/releases/download/v0.3.1/syokan-linux-arm64"
      sha256 "f222fbb7012dcb20e50c6ed432abdf699868395f655699d2d0c2b90502d656a4"
    end
    on_intel do
      url "https://github.com/wwwyo/syokan/releases/download/v0.3.1/syokan-linux-x64"
      sha256 "40e17a5526bce8289f9a03b8f5b847ab4d0e2b0c99cb8ba2b03f08841af52316"
    end
  end

  def install
    bin.install Dir["syokan-*"].first => "syokan"
  end

  test do
    assert_match "0.3.1", shell_output("#{bin}/syokan --version")
  end
end
