# Generated by apps/syokan/scripts/generate-formula.ts in wwwyo/syokan (release 0.3.0).
# Do not edit by hand — the next release overwrites this file.
class Syokan < Formula
  desc "LLMs summon rich UI: post a JSON tree, an ephemeral view appears"
  homepage "https://github.com/wwwyo/syokan"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/wwwyo/syokan/releases/download/v0.3.0/syokan-darwin-arm64"
      sha256 "530128ac9b5d018ca2143cf96e62c772835405404860db306f32697b860f42cc"
    end
    on_intel do
      url "https://github.com/wwwyo/syokan/releases/download/v0.3.0/syokan-darwin-x64"
      sha256 "950fdb348ee0e3483fd2c3793e38206ad920e13919c69cd5ebde6e8961aaab52"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/wwwyo/syokan/releases/download/v0.3.0/syokan-linux-arm64"
      sha256 "b6aa103b65e887bd2cc18c6f00f71667724c2bdfb4ba42023cc06e651f360147"
    end
    on_intel do
      url "https://github.com/wwwyo/syokan/releases/download/v0.3.0/syokan-linux-x64"
      sha256 "aefab7216be6c306c0d5435d86a9cad3e01ce02d4bd657d74f463c2d55bc9399"
    end
  end

  def install
    bin.install Dir["syokan-*"].first => "syokan"
  end

  test do
    assert_match "0.3.0", shell_output("#{bin}/syokan --version")
  end
end
